export const INTERESTS = [
  'Hiking',
  'Yoga',
  'Cooking',
  'Photography',
  'Music',
  'Reading',
  'Travel',
  'Fitness',
  'Art',
  'Movies',
  'Coffee',
  'Wine',
  'Dancing',
  'Gaming',
  'Running',
  'Cycling',
  'Swimming',
  'Meditation',
  'Fashion',
  'Food',
  'Theater',
  'Concerts',
  'Museums',
  'Volunteering',
  'Pets',
  'Beach',
  'Mountains',
  'Sports',
  'Comedy',
  'Writing',
];

export const PERSONALITY_TRAITS = [
  'Adventurous',
  'Outgoing',
  'Introverted',
  'Creative',
  'Intellectual',
  'Funny',
  'Ambitious',
  'Laid-back',
  'Romantic',
  'Spontaneous',
  'Organized',
  'Empathetic',
  'Confident',
  'Thoughtful',
  'Energetic',
  'Calm',
  'Optimistic',
  'Passionate',
  'Open-minded',
  'Loyal',
];

export const EVENT_CATEGORIES = [
  { id: 'food_drink' as const, name: 'Food & Drink', emoji: '🍷' },
  { id: 'outdoor' as const, name: 'Outdoor', emoji: '🌳' },
  { id: 'entertainment' as const, name: 'Entertainment', emoji: '🎬' },
  { id: 'sports' as const, name: 'Sports & Fitness', emoji: '⚽' },
  { id: 'arts_culture' as const, name: 'Arts & Culture', emoji: '🎨' },
  { id: 'social' as const, name: 'Social', emoji: '🎉' },
  { id: 'other' as const, name: 'Other', emoji: '✨' },
];
